apiVersion: v1
kind: PersistentVolume
metadata:
  name: jk8s-pv
  namespace: jk8s
spec:
  storageClassName: jk8s-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /big1/jk8s/

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jk8s-pv
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
